apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: orders
data:
  POSTGRES_DB: ordersdb
  POSTGRES_USER: orders_user

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: orders
type: Opaque
stringData:
  POSTGRES_PASSWORD: orders_pass

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: orders
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432